spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health_reporting
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: secret
    baseline-description: "initial schema"
    baseline-version: 1
    locations: classpath:db/migration